#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jun  4 18:41:38 2017

@author: gabrui
"""

from FichaUsuario.models import GenreModel 

def criarModels():
    generos = ["Tourist Hotspots", "Bussiness", "Social", "Dating" ]
    for genero in generos:
        if not GenreModel.objects.filter(name = genero):
            modelo = GenreModel(name = genero)
            modelo.save()