# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FichaUsuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='algum_logo',
            new_name='album_logo',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='algum_title',
            new_name='album_title',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='name',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(default='mypassword', max_length=100),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='username',
            field=models.CharField(default='myusername', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email_account',
            field=models.EmailField(default='myaccount@emaildomain.com', max_length=250, unique=True),
        ),
    ]
